### ISSUE TITLE
Minecraft crash with guiAPI and ID resolver

### ISSUE THREAD

**Issue by ghost** [LO6AN/New-Frontier-Craft#58]
Minecraft has crashed!      
      ----------------------      

Minecraft has stopped running because it encountered a problem.

If you wish to report this, please copy this entire text and send it to our Discord. The button below will take you there.
If the button below doesn't work, you can find our Discord on this website: https://newfrontiercraft.net/thread/51/front-page
In our Discord, there is a #bug-reports channel you can use. If you show us the error, be sure to use Pastebin to reduce channel clutter.
Please include a description of what you did when the error occured.

--- BEGIN ERROR REPORT 6f38a48c --------
Generated 7/5/21 1:57 PM

Minecraft: Beta 1.7.3
New Frontier Craft: v3.4.0
OS: Windows 10 (amd64) version 10.0
Java: 1.8.0_291, Oracle Corporation
VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
LWJGL: 2.9.4
OpenGL: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 version 4.6.0 NVIDIA 466.77, NVIDIA Corporation

java.lang.RuntimeException: You should never see this. For some reason, ID resolver attempted to get an item name for null, or a class that isn't a block or item.
	at IDResolver.GetlongName(IDResolver.java:304)
	at IDResolver.<init>(IDResolver.java:1104)
	at IDResolver.GetConflictedBlockID(IDResolver.java:168)
	at uu.<init>(Block.java:49)
	at uu.<init>(Block.java:78)
	at ah.<init>(BlockTNT.java:20)
	at betatweaks.block.BlockTNTPunchable.<init>(BlockTNTPunchable.java:12)
	at betatweaks.BetaTweaks.initSettings(BetaTweaks.java:65)
	at betatweaks.BetaTweaks.init(BetaTweaks.java:39)
	at mod_BetaTweaks.<init>(mod_BetaTweaks.java:9)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at ModLoader.addMod(ModLoader.java:224)
	at ModLoader.readFromModFolder(ModLoader.java:1111)
	at ModLoader.init(ModLoader.java:718)
	at ModLoader.AddAllRenderers(ModLoader.java:121)
	at th.<init>(RenderManager.java:94)
	at th.<clinit>(RenderManager.java:201)
	at net.minecraft.client.Minecraft.a(Minecraft.java:273)
	at net.minecraft.client.Minecraft.run(Minecraft.java:547)
	at java.lang.Thread.run(Unknown Source)
--- END ERROR REPORT 3c9f7271 ----------

**Comment by Roadhog360** [comment]
This issue tracker is for vanilla issues. Issues with mods and addons should be reported to the authors or their issue trackers instead.
